-- Database: adventureworks

-- DROP DATABASE IF EXISTS adventureworks;

CREATE DATABASE adventureworks
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Vietnamese_Vietnam.1258'
    LC_CTYPE = 'Vietnamese_Vietnam.1258'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
CREATE TABLE Custom(
	ID INT PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	ADDRESS_City VARCHAR(50) NOT NULL,
	StateProvince VARCHAR(50) NOT NULL
	)
--DROP TABLE Custom;
CREATE TABLE Products(
	PRODUCT_NUMBER VARCHAR(30) PRIMARY KEY NOT NULL,
	NAME_P VARCHAR(30) NOT NULL,
	COLOR_P VARCHAR(10) NOT NULL,
	SIZE_P CHAR(3) NOT NULL,
	PRICE_P MONEY NOT NULL,
	WEIGHT_P SMALLINT NOT NULL
)
--DROP TABLE Products;
INSERT INTO Custom (ID, Name, ADDRESS_City, StateProvince)
VALUES ('01','Vu Tien Dung', 'Ha Noi', 'Truong Dinh');
INSERT INTO Custom (ID, Name, ADDRESS_City, StateProvince)
VALUES ('02','Le Huy Hoang', 'Nam Dinh' ,'Y Yen');
INSERT INTO Custom (ID, Name, ADDRESS_City, StateProvince)
VALUES ('03','Hoang Nhat Hung', 'Ha Noi', 'Hoang Mai');
INSERT INTO Custom (ID, Name, ADDRESS_City, StateProvince)
VALUES ('04','Tran Vu Truong Giang', 'Ninh Binh', 'Yen Loc');
SELECT * FROM Custom;

INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P, WEIGHT_P)
VALUES ('BK-51565','DELL V', 'Black', 'M', '16000000', '4');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P, WEIGHT_P)
VALUES ('BK-83478r','Thinkpad', 'White', 'L', '20000000', '3');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P, WEIGHT_P)
VALUES ('AK-93825r','ACCER X', 'Red', 'S', '24000000', '5');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-786482','MAC XS', 'Blue', 'XL', '30000000', '5');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-356482','LENOVO 10', 'White', 'XL', '30000000', '2');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-7832952','MAC CLC', 'RED', 'M', '30000000', '3');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-78648947','DELL IMPRI', 'Black', 'S', '20000000', '7');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-72534582','ASUS 10', 'RED', 'XL', '10000000', '8');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-76534682','MAC XL', 'Black', 'XL', '11000000', '8');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-3253482','MAC XU', 'Green', 'XL', '15000000', '6');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-532482','DELL XA', 'Violet', 'XL', '12000000', '5');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-2352482','ASSUS11', 'Pink', 'XL', '18000000', '7');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-7465382','LENOVO QK', 'Orange', 'XL', '16000000', '4');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-7893755','NOKIA', 'Black', 'M', '26000000', '3');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-345482','IP 13 PR mAX', 'Green', 'XL', '30000000', '10');
INSERT INTO Products (PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P)
VALUES ('BK-7863462','Sam Sung', 'Blue', 'XL', '30000000', '4');
SELECT * FROM Products;

--Truy van
--Task 1:
--1. Truy van thong tin ten cac thanh pho, tinh sap xep theo thu tu tang dan ten thanh pho

SELECT ADDRESS_City, StateProvince AS SalesLT_Address
FROM Custom
ORDER BY ADDRESS_City ASC;

--2 Truy xuat du lieu san pham  lay top 10 san pham nang nhat
SELECT PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P FROM (
	SELECT PRODUCT_NUMBER, NAME_P, COLOR_P, SIZE_P, PRICE_P,WEIGHT_P 
	FROM Products
	ORDER BY WEIGHT_P DESC
)AS SORT_WEIGHT
LIMIT 10* (SELECT COUNT(PRODUCT_NUMBER) FROM Products) / 100;

--TASK 2:
--1. Lay thong tin chi tiet ve san pham theo ma ID cho trc
SELECT NAME_P, COLOR_P, SIZE_P FROM Products
WHERE PRODUCT_NUMBER LIKE '%BK-7863462%'; 

--2. Loc san pham theo mau sac va kich thuoc
SELECT PRODUCT_NUMBER, NAME_P FROM Products
WHERE (COLOR_P ='Black' OR COLOR_P = 'Red' OR COLOR_P = 'White') AND (SIZE_P = 'S' OR SIZE_P ='M');

--3. LOc san pham theo so san pham 
SELECT PRODUCT_NUMBER, NAME_P, PRICE_P FROM Products
WHERE PRODUCT_NUMBER LIKE 'BK%';

--4. Truy xuat cac san pham cu the theo so san pham
SELECT PRODUCT_NUMBER, NAME_P, PRICE_P FROM Products
WHERE  PRODUCT_NUMBER LIKE 'BK%' AND PRODUCT_NUMBER NOT LIKE '%r%' 
AND(PRODUCT_NUMBER LIKE '%01'
	OR PRODUCT_NUMBER LIKE '%02'
   	OR PRODUCT_NUMBER LIKE '%03'
	OR PRODUCT_NUMBER LIKE '%04'
	OR PRODUCT_NUMBER LIKE '%05'
	OR PRODUCT_NUMBER LIKE '%06'
	OR PRODUCT_NUMBER LIKE '%07'
	OR PRODUCT_NUMBER LIKE '%08'
	OR PRODUCT_NUMBER LIKE '%09'
	OR PRODUCT_NUMBER LIKE '%10'
	OR PRODUCT_NUMBER LIKE '%5_'
   
   
   )

